services:
  postgres:
    image: postgres:16-alpine
    container_name: ims-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: ims-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ims_datalake
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    container_name: ims-redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: ims-backend
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "9595:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: ims-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://10.10.69.109:9595/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
  mongodata: